# -*- coding: utf-8 -*-
"""100-pandas-puzzles v.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a9TLc1549fThM0gTfkAWWCuqdg4Xj0ZV
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Optional (best interactive charts)
# pip install plotly
import plotly.express as px

plt.style.use("seaborn-v0_8")
sns.set_theme()

print("Pandas version:", pd.__version__)
pd.show_versions()

data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = list("abcdefghij")
df = pd.DataFrame(data, index=labels)
df

df.info()
df.describe()

df.head(3)
df[['animal', 'age']]
df.loc[df.index[[3,4,8]], ['animal','age']]
df[df['visits'] > 2]
df[df['age'].isna()]
df[(df['animal'] == 'cat') & (df['age'] < 3)]
df[df['age'].between(2,4, inclusive="both")]

df.loc['f','age'] = 1.5
df['visits'].sum()
df.groupby('animal')['age'].mean()
df['animal'].value_counts()

df.sort_values(['age','visits'], ascending=[False, True])

df['priority'] = df['priority'].map({'yes':True,'no':False})
df['animal'] = df['animal'].replace({'snake':'python'})
df.pivot_table(index='animal', columns='visits', values='age', aggfunc='mean')

df2 = pd.DataFrame({'A':[1,2,2,3,4,5,5,6,7,7]})
df2[df2['A'] != df2['A'].shift()]

df3 = pd.DataFrame(np.random.rand(5,3))
df3.sub(df3.mean(axis=1), axis=0)

df4 = pd.DataFrame(np.random.rand(5,10), columns=list("abcdefghij"))
df4.sum().idxmin()
(df.isna().cumsum(axis=1) == 3).idxmax(axis=1)

df5 = pd.DataFrame({
    'grps': list('aaabbcaabcccbbc'),
    'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]
})

df5.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())

dates = pd.date_range("2015-01-01", "2015-12-31", freq="B")
s = pd.Series(np.random.rand(len(dates)), index=dates)
s[s.index.weekday == 2].sum()          # Wednesdays
s.resample("ME").mean()                # Monthly mean
s.groupby(pd.Grouper(freq="4ME")).idxmax()
pd.date_range("2015-01-01","2016-12-31",freq="WOM-3THU")

df = pd.DataFrame({
    'From_To': ['LoNDon_paris','MAdrid_miLAN','londON_StockhOlm',
                'Budapest_PaRis','Brussels_londOn'],
    'FlightNumber':[10045,np.nan,10065,np.nan,10085],
    'RecentDelays':[[23,47],[],[24,43,87],[13],[67,32]],
    'Airline':['KLM(!)','<Air France> (12)',
               '(British Airways. )','12. Air France','"Swiss Air"']
})

# Fix flight numbers
df['FlightNumber'] = df['FlightNumber'].interpolate().astype(int)

# Split From_To
temp = df['From_To'].str.split('_', expand=True)
temp.columns = ['From', 'To']
temp = temp.apply(lambda x: x.str.lower().str.capitalize())

df = df.drop(columns='From_To').join(temp)

# AIRLINE CLEANING
df['Airline'] = (
    df['Airline']
    .str.extract(r'([A-Za-z\s]+)', expand=False)
    .str.strip()
)

# Expand delays
delays = df['RecentDelays'].apply(pd.Series)
delays.columns = [f'delay_{i}' for i in range(1, delays.shape[1] + 1)]

df = df.drop(columns='RecentDelays').join(delays)

df

sns.countplot(data=df, x='Airline')
plt.title("Flights by Airline")
plt.show()

px.bar(df, x='Airline', y='delay_1', title="First Delay by Airline")

sns.scatterplot(data=df, x='delay_1', y='delay_2', hue='Airline', s=150)
plt.show()

